services:
    test-mysql:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
              UID: $UserUID
        container_name: 'test_web_mysql'
        extra_hosts:
            - 'host.docker.internal:host-gateway'

        ports:
            - '${APP_PORT:-80}:80'

        volumes:
            - './www:/var/www/html'

        working_dir: '/var/www/html'

        networks:
            - default

        depends_on: {  }

networks:
  default:
    external: true
    name: docker-compose-mysql_net_mysql