services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql_dev'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_PASSWORD: 'root'
    volumes:
      - './Data:/var/lib/mysql'
    networks:
      - net_mysql

    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

networks:
  net_mysql:
      driver: bridge
